In [ ]:
# VARIABLES

var1 = 78
# integer data type can +ve or -ve or 0
var2 = 67.89
# floating point number : both +ve and -ve
var3 = "Python"
# string :text value, alphanumeric value
var4 = "programming"
var5 = True
# Boolean : only two value : True and false
var6 = False
# Boolean
print(var1)
print(var2)
print(var3)
print(var4)
print(var5)
print(var6)

print(type(var1))
print(type(var2))
print(type(var3))
print(type(var4))
print(type(var5))
print(type(var6))

In [ ]:
print(var1,var2,var3,var4)

In [ ]:
base_salary = 10_000_000
print(base_salary)
allowances = 10_000
print(allowances)
tax = 5000

net_salary =base_salary + allowances - tax
print(net_salary)

In [ ]:
list1 = [10,20,30,40,50,60]
sum1 = sum(list1)

print(sum1)

In [ ]:
import numpy as np
# machine learning library : scikit - learn
import sklearn

In [ ]:
# INDENTATION : means spacing before the command
import numpy as np
v = np.array([10, 20, 30]) # 1D = single row # vector
m = np.array( [
              [1,2,3],
             [4,5,6],
             [7,8,9],
             [10,11,12],
             [13,14,15]
             ]
             ) #2Dlist = rows and columns : 5x3 # MATRIX
print("v:" , v, "shape:", v.shape)
print("m:\n", m, "\nshape:" , m.shape)
# \n means newline in output
# comments

In [ ]:
import pandas as pd

df = pd.read_csv("sales-revenue-business-dataset.csv")

print(df)

       index       Date    Year     Month  Customer Age Customer Gender  \
0          0  2/19/2016  2016.0  February          29.0               F
1          1  2/20/2016  2016.0  February          29.0               F
2          2  2/27/2016  2016.0  February          29.0               F
3          3  3/12/2016  2016.0     March          29.0               F
4          4  3/12/2016  2016.0     March          29.0               F
...      ...        ...     ...       ...           ...             ...
34862  34862   2/7/2016  2016.0  February          38.0               M
34863  34863  3/13/2015  2015.0     March          38.0               M
34864  34864   4/5/2015  2015.0     April          38.0               M
34865  34865  8/30/2015  2015.0    August          38.0               M
34866  34866        NaN     NaN       NaN           NaN             NaN

             Country           State Product Category     Sub Category  \
0      United States      Washington      Accessories  Tires and Tubes
1      United States      Washington         Clothing           Gloves
2      United States      Washington      Accessories  Tires and Tubes
3      United States      Washington      Accessories  Tires and Tubes
4      United States      Washington      Accessories  Tires and Tubes
...              ...             ...              ...              ...
34862         France  Hauts de Seine            Bikes   Mountain Bikes
34863         France  Hauts de Seine            Bikes   Mountain Bikes
34864         France  Hauts de Seine            Bikes   Mountain Bikes
34865         France  Hauts de Seine            Bikes   Mountain Bikes
34866            NaN             NaN              NaN              NaN

       Quantity  Unit Cost   Unit Price    Cost      Revenue  Column1
0           1.0      80.00   109.000000    80.0   109.000000      NaN
1           2.0      24.50    28.500000    49.0    57.000000      NaN
2           3.0       3.67     5.000000    11.0    15.000000      NaN
3           2.0      87.50   116.500000   175.0   233.000000      NaN
4           3.0      35.00    41.666667   105.0   125.000000      NaN
...         ...        ...          ...     ...          ...      ...
34862       2.0    1160.00   985.500000  2320.0  1971.000000      NaN
34863       1.0    2049.00  1583.000000  2049.0  1583.000000      NaN
34864       3.0     683.00   560.666667  2049.0  1682.000000      NaN
34865       1.0    2320.00  1568.000000  2320.0  1568.000000      NaN
34866       NaN        NaN          NaN     NaN   641.532095      NaN

[34867 rows x 16 columns]

In [ ]:
df

,index,Date,Year,Month,Customer Age,Customer Gender,Country,State,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Cost,Revenue,Column1
0,0,2/19/2016,2016.0,February,29.0,F,United States,Washington,Accessories,Tires and Tubes,1.0,80.00,109.000000,80.0,109.000000,NaN
1,1,2/20/2016,2016.0,February,29.0,F,United States,Washington,Clothing,Gloves,2.0,24.50,28.500000,49.0,57.000000,NaN
2,2,2/27/2016,2016.0,February,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,3.67,5.000000,11.0,15.000000,NaN
3,3,3/12/2016,2016.0,March,29.0,F,United States,Washington,Accessories,Tires and Tubes,2.0,87.50,116.500000,175.0,233.000000,NaN
4,4,3/12/2016,2016.0,March,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,35.00,41.666667,105.0,125.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34862,34862,2/7/2016,2016.0,February,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,2.0,1160.00,985.500000,2320.0,1971.000000,NaN
34863,34863,3/13/2015,2015.0,March,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,1.0,2049.00,1583.000000,2049.0,1583.000000,NaN
34864,34864,4/5/2015,2015.0,April,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,3.0,683.00,560.666667,2049.0,1682.000000,NaN
34865,34865,8/30/2015,2015.0,August,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,1.0,2320.00,1568.000000,2320.0,1568.000000,NaN
34866,34866,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,641.532095,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34867 entries, 0 to 34866
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             34867 non-null  int64
 1   Date              34866 non-null  object
 2   Year              34866 non-null  float64
 3   Month             34866 non-null  object
 4   Customer Age      34866 non-null  float64
 5   Customer Gender   34866 non-null  object
 6   Country           34866 non-null  object
 7   State             34866 non-null  object
 8   Product Category  34866 non-null  object
 9   Sub Category      34866 non-null  object
 10  Quantity          34866 non-null  float64
 11  Unit Cost         34866 non-null  float64
 12  Unit Price        34866 non-null  float64
 13  Cost              34866 non-null  float64
 14  Revenue           34867 non-null  float64
 15  Column1           2574 non-null   float64
dtypes: float64(8), int64(1), object(7)
memory usage: 4.3+ MB

In [ ]:
df.describe()

,index,Year,Customer Age,Quantity,Unit Cost,Unit Price,Cost,Revenue,Column1
count,34867.000000,34866.000000,34866.000000,34866.000000,34866.000000,34866.000000,34866.000000,34867.000000,2574.000000
mean,17433.000000,2015.569237,36.382895,2.002524,349.880567,389.232485,576.004532,640.870093,688.054913
std,10065.380254,0.495190,11.112902,0.813936,490.015846,525.319091,690.500395,736.640033,774.200897
min,0.000000,2015.000000,17.000000,1.000000,0.670000,0.666667,2.000000,2.000000,2.000000
25%,8716.500000,2015.000000,28.000000,1.000000,45.000000,53.666667,85.000000,102.000000,104.250000
50%,17433.000000,2016.000000,35.000000,2.000000,150.000000,179.000000,261.000000,319.000000,390.500000
75%,26149.500000,2016.000000,44.000000,3.000000,455.000000,521.000000,769.000000,902.000000,975.750000
max,34866.000000,2016.000000,87.000000,3.000000,3240.000000,5082.000000,3600.000000,5082.000000,3681.000000

In [ ]:
list1 = [10,20,50,40,70,80,5]
# sort in ascending order
# 5,10,20,40,50,70,80
# total data points = 7
# median = avg of middle two position = 40
#40+50 / 2 = 90/2 = 45

#3,3,4,4,4,6,6,2,1,113,4,5,6,7
#3 is occuring 3 times
#4 is occuring 4 times
#mode = 4

In [ ]:
df['Year']

0        2016.0
1        2016.0
2        2016.0
3        2016.0
4        2016.0
          ...
34862    2016.0
34863    2015.0
34864    2015.0
34865    2015.0
34866       NaN
Name: Year, Length: 34867, dtype: float64

In [ ]:
df["Year"].unique()

array([2016., 2015.,   nan])

In [ ]:
df["Country"].unique()

array(['United States', 'France', 'United Kingdom', 'Germany', nan],
      dtype=object)

In [ ]:
# DATA PRE PROCESSING

df = df.drop('Column1', axis=1)

In [ ]:
df.columns

Index(['index', 'Date', 'Year', 'Month', 'Customer Age', 'Customer Gender',
       'Country', 'State', 'Product Category', 'Sub Category', 'Quantity',
       'Unit Cost', 'Unit Price', 'Cost', 'Revenue'],
      dtype='object')

In [ ]:
df.isnull()

,index,Date,Year,Month,Customer Age,Customer Gender,Country,State,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Cost,Revenue
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34862,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
34863,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
34864,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
34865,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
34866,False,True,True,True,True,True,True,True,True,True,True,True,True,True,False

In [ ]:
# missing the filling values
# filling means replace the NaN values wtih 0
df.fillna(0)

,index,Date,Year,Month,Customer Age,Customer Gender,Country,State,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Cost,Revenue
0,0,2/19/2016,2016.0,February,29.0,F,United States,Washington,Accessories,Tires and Tubes,1.0,80.00,109.000000,80.0,109.000000
1,1,2/20/2016,2016.0,February,29.0,F,United States,Washington,Clothing,Gloves,2.0,24.50,28.500000,49.0,57.000000
2,2,2/27/2016,2016.0,February,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,3.67,5.000000,11.0,15.000000
3,3,3/12/2016,2016.0,March,29.0,F,United States,Washington,Accessories,Tires and Tubes,2.0,87.50,116.500000,175.0,233.000000
4,4,3/12/2016,2016.0,March,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,35.00,41.666667,105.0,125.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34862,34862,2/7/2016,2016.0,February,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,2.0,1160.00,985.500000,2320.0,1971.000000
34863,34863,3/13/2015,2015.0,March,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,1.0,2049.00,1583.000000,2049.0,1583.000000
34864,34864,4/5/2015,2015.0,April,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,3.0,683.00,560.666667,2049.0,1682.000000
34865,34865,8/30/2015,2015.0,August,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,1.0,2320.00,1568.000000,2320.0,1568.000000
34866,34866,0,0.0,0,0.0,0,0,0,0,0,0.0,0.00,0.000000,0.0,641.532095

In [ ]:
# dropna()will remove the entire row with NaN value
df = df.dropna()

In [ ]:
df

,index,Date,Year,Month,Customer Age,Customer Gender,Country,State,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Cost,Revenue,Profit
0,0,2/19/2016,2016.0,February,29.0,F,United States,Washington,Accessories,Tires and Tubes,1.0,80.00,109.000000,80.0,109.0,29.0
1,1,2/20/2016,2016.0,February,29.0,F,United States,Washington,Clothing,Gloves,2.0,24.50,28.500000,49.0,57.0,8.0
2,2,2/27/2016,2016.0,February,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,3.67,5.000000,11.0,15.0,4.0
3,3,3/12/2016,2016.0,March,29.0,F,United States,Washington,Accessories,Tires and Tubes,2.0,87.50,116.500000,175.0,233.0,58.0
4,4,3/12/2016,2016.0,March,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,35.00,41.666667,105.0,125.0,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34861,34861,3/22/2015,2015.0,March,38.0,M,France,Charente-Maritime,Bikes,Mountain Bikes,1.0,2049.00,1487.000000,2049.0,1487.0,-562.0
34862,34862,2/7/2016,2016.0,February,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,2.0,1160.00,985.500000,2320.0,1971.0,-349.0
34863,34863,3/13/2015,2015.0,March,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,1.0,2049.00,1583.000000,2049.0,1583.0,-466.0
34864,34864,4/5/2015,2015.0,April,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,3.0,683.00,560.666667,2049.0,1682.0,-367.0
34865,34865,8/30/2015,2015.0,August,38.0,M,France,Hauts de Seine,Bikes,Mountain Bikes,1.0,2320.00,1568.000000,2320.0,1568.0,-752.0

In [ ]:
df.to_csv("cleaned_sales_dataset.csv")

In [ ]:
#Feature Engineering

df = df.drop("Unnamed: 0" , axis = 1)

In [ ]:
df.columns

Index(['index', 'Date', 'Year', 'Month', 'Customer Age', 'Customer Gender',
       'Country', 'State', 'Product Category', 'Sub Category', 'Quantity',
       'Unit Cost', 'Unit Price', 'Cost', 'Revenue'],
      dtype='object')

In [ ]:
# Create a new column
df['Profit'] = df['Revenue'] - df['Cost']

In [ ]:
df.head()
# .head() shows top 5 rows
# .tail() shows bottom 5 rows

In [ ]:
# Create Profit margin column
df['Profit_margin'] = df['Profit'] / df['Revenue'] * 100

In [ ]:
df.head()

df.to_csv("feature_enfineering_sales_dataset.csv")

In [ ]:
# encoding

# LABEL ENCODING

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Customer Gender'] = le.fit_transform(df['Customer Gender'])

In [ ]:
# find the unique values
# unique values = M and F
# F = 0 and M = 1
# M will get replaced by 1
# F will get replaced by 0

In [ ]:
df['Customer Gender']

0        F
1        F
2        F
3        F
4        F
        ..
34861    M
34862    M
34863    M
34864    M
34865    M
Name: Customer Gender, Length: 34866, dtype: object

In [ ]:
df['Country'] = le.fit_transform(df['Country'])
df['Month'] = le.fit_transform(df['Month'])
df['State'] = le.fit_transform(df['State'])
df['Sub category'] = le.fit_transform(df['Sub category'])

In [ ]:
df.head(50)

,index,Date,Year,Month,Customer Age,Customer Gender,Country,State,Product Category,Sub Category,Quantity,Unit Cost,Unit Price,Cost,Revenue,Profit
0,0,2/19/2016,2016.0,February,29.0,F,United States,Washington,Accessories,Tires and Tubes,1.0,80.00,109.000000,80.0,109.0,29.0
1,1,2/20/2016,2016.0,February,29.0,F,United States,Washington,Clothing,Gloves,2.0,24.50,28.500000,49.0,57.0,8.0
2,2,2/27/2016,2016.0,February,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,3.67,5.000000,11.0,15.0,4.0
3,3,3/12/2016,2016.0,March,29.0,F,United States,Washington,Accessories,Tires and Tubes,2.0,87.50,116.500000,175.0,233.0,58.0
4,4,3/12/2016,2016.0,March,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,35.00,41.666667,105.0,125.0,20.0
5,5,4/8/2016,2016.0,April,29.0,F,United States,Washington,Accessories,Tires and Tubes,1.0,66.00,78.000000,66.0,78.0,12.0
6,6,4/17/2016,2016.0,April,29.0,F,United States,Washington,Accessories,Tires and Tubes,2.0,52.00,60.000000,104.0,120.0,16.0
7,7,4/17/2016,2016.0,April,29.0,F,United States,Washington,Accessories,Tires and Tubes,1.0,60.00,68.000000,60.0,68.0,8.0
8,8,6/22/2016,2016.0,June,29.0,F,United States,Washington,Accessories,Tires and Tubes,2.0,8.00,10.000000,16.0,20.0,4.0
9,9,6/22/2016,2016.0,June,29.0,F,United States,Washington,Accessories,Tires and Tubes,2.0,2.50,3.000000,5.0,6.0,1.0
10,10,6/24/2016,2016.0,June,29.0,F,United States,Washington,Accessories,Helmets,2.0,17.50,21.000000,35.0,42.0,7.0
11,11,7/1/2016,2016.0,July,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,40.00,48.666667,120.0,146.0,26.0
12,12,7/22/2016,2016.0,July,29.0,F,United States,Washington,Accessories,Tires and Tubes,2.0,46.00,60.000000,92.0,120.0,28.0
13,13,7/22/2016,2016.0,July,29.0,F,United States,Washington,Accessories,Tires and Tubes,1.0,9.00,10.000000,9.0,10.0,1.0
14,14,8/18/2015,2015.0,August,29.0,F,United States,Washington,Accessories,Helmets,3.0,151.67,181.333333,455.0,544.0,89.0
15,15,8/30/2015,2015.0,August,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,70.00,72.666667,210.0,218.0,8.0
16,16,9/17/2015,2015.0,September,29.0,F,United States,Washington,Accessories,Tires and Tubes,1.0,385.00,439.000000,385.0,439.0,54.0
17,17,9/17/2015,2015.0,September,29.0,F,United States,Washington,Accessories,Tires and Tubes,2.0,72.50,86.500000,145.0,173.0,28.0
18,18,9/17/2015,2015.0,September,29.0,F,United States,Washington,Accessories,Helmets,3.0,210.00,212.666667,630.0,638.0,8.0
19,19,9/24/2015,2015.0,September,29.0,F,United States,Washington,Accessories,Tires and Tubes,1.0,64.00,74.000000,64.0,74.0,10.0
20,20,9/24/2015,2015.0,September,29.0,F,United States,Washington,Accessories,Helmets,3.0,326.67,359.666667,980.0,1079.0,99.0
21,21,10/7/2015,2015.0,October,29.0,F,United States,Washington,Accessories,Tires and Tubes,1.0,125.00,136.000000,125.0,136.0,11.0
22,22,10/7/2015,2015.0,October,29.0,F,United States,Washington,Accessories,Helmets,2.0,17.50,18.000000,35.0,36.0,1.0
23,23,10/7/2015,2015.0,October,29.0,F,United States,Washington,Accessories,Tires and Tubes,2.0,215.00,226.000000,430.0,452.0,22.0
24,24,10/7/2015,2015.0,October,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,22.00,23.000000,66.0,69.0,3.0
25,25,10/13/2015,2015.0,October,29.0,F,United States,Washington,Accessories,Tires and Tubes,1.0,750.00,820.000000,750.0,820.0,70.0
26,26,10/20/2015,2015.0,October,29.0,F,United States,Washington,Accessories,Tires and Tubes,2.0,60.00,70.500000,120.0,141.0,21.0
27,27,10/20/2015,2015.0,October,29.0,F,United States,Washington,Accessories,Tires and Tubes,1.0,125.00,130.000000,125.0,130.0,5.0
28,28,10/20/2015,2015.0,October,29.0,F,United States,Washington,Accessories,Helmets,1.0,140.00,143.000000,140.0,143.0,3.0
29,29,11/1/2015,2015.0,November,29.0,F,United States,Washington,Accessories,Tires and Tubes,2.0,192.50,213.500000,385.0,427.0,42.0
30,30,11/1/2015,2015.0,November,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,38.33,43.333333,115.0,130.0,15.0
31,31,11/1/2015,2015.0,November,29.0,F,United States,Washington,Accessories,Helmets,3.0,151.67,170.000000,455.0,510.0,55.0
32,32,11/15/2015,2015.0,November,29.0,F,United States,Washington,Accessories,Tires and Tubes,1.0,56.00,65.000000,56.0,65.0,9.0
33,33,11/15/2015,2015.0,November,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,108.67,123.666667,326.0,371.0,45.0
34,34,11/15/2015,2015.0,November,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,14.67,15.000000,44.0,45.0,1.0
35,35,12/15/2015,2015.0,December,29.0,F,United States,Washington,Accessories,Helmets,2.0,280.00,269.000000,560.0,538.0,-22.0
36,36,12/16/2015,2015.0,December,29.0,F,United States,Washington,Accessories,Tires and Tubes,2.0,293.50,320.500000,587.0,641.0,54.0
37,37,12/16/2015,2015.0,December,29.0,F,United States,Washington,Accessories,Tires and Tubes,2.0,2.00,2.000000,4.0,4.0,0.0
38,38,12/16/2015,2015.0,December,29.0,F,United States,Washington,Accessories,Helmets,1.0,420.00,472.000000,420.0,472.0,52.0
39,39,12/20/2015,2015.0,December,29.0,F,United States,Washington,Accessories,Tires and Tubes,2.0,275.50,303.000000,551.0,606.0,55.0
40,40,12/20/2015,2015.0,December,29.0,F,United States,Washington,Accessories,Tires and Tubes,1.0,120.00,120.000000,120.0,120.0,0.0
41,41,12/20/2015,2015.0,December,29.0,F,United States,Washington,Accessories,Helmets,1.0,630.00,624.000000,630.0,624.0,-6.0
42,42,12/25/2015,2015.0,December,29.0,F,United States,Washington,Accessories,Tires and Tubes,2.0,32.50,36.000000,65.0,72.0,7.0
43,43,12/25/2015,2015.0,December,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,338.33,389.333333,1015.0,1168.0,153.0
44,44,12/25/2015,2015.0,December,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,10.67,11.000000,32.0,33.0,1.0
45,45,12/29/2015,2015.0,December,29.0,F,United States,Washington,Accessories,Tires and Tubes,3.0,36.67,41.666667,110.0,125.0,15.0
46,46,12/29/2015,2015.0,December,29.0,F,United States,Washington,Accessories,Helmets,2.0,245.00,249.500000,490.0,499.0,9.0
47,47,7/22/2015,2015.0,July,18.0,F,United States,California,Accessories,Bike Stands,1.0,636.00,677.000000,636.0,677.0,41.0
48,48,10/10/2015,2015.0,October,18.0,F,United States,California,Accessories,Bike Stands,3.0,159.00,170.666667,477.0,512.0,35.0
49,49,6/11/2016,2016.0,June,18.0,M,United States,California,Bikes,Mountain Bikes,1.0,769.00,875.000000,769.0,875.0,106.0

In [ ]:
# One Hot Encoding


df = df.get_dummmies( 'Product category')
encoded = pd.concat([df,encoded], axis = 1)

In [ ]:
df = df.concat((encoded), axis = 1)

In [ ]:
df.columns

Index(['index', 'Date', 'Year', 'Month', 'Customer Age', 'Customer Gender',
       'Country', 'State', 'Product Category', 'Sub Category', 'Quantity',
       'Unit Cost', 'Unit Price', 'Cost', 'Revenue', 'Profit'],
      dtype='object')

In [ ]:
df = df.drop(['Index', 'Date', 'Year', 'Product_Category', 'Product_Category_Accessories',
'Product Category_Bikes', 'Product Category_Clothing'], axis=1)

KeyError: "['Index', 'Product_Category', 'Product_Category_Accessories', 'Product Category_Bikes', 'Product Category_Clothing'] not found in axis"

In [ ]:
df.columns

Index(['Date', 'Year', 'Month', 'Customer Age', 'Customer Gender', 'Country',
       'State', 'Product Category', 'Sub Category', 'Quantity', 'Unit Cost',
       'Unit Price', 'Cost', 'Revenue', 'Profit'],
      dtype='object')

In [ ]:
# Linear Regression

In [ ]:
from google.colab import drive
drive.mount('/content/drive')